print("Hello World!")
print("Welcome to Python programming.")                             
print("This is my first program.")
print("I am excited to learn more about coding.")   
print("Let's write more programs together! , Goodbye for now.")